### ISSUE TITLE
iconfont 的一个眼睛图标会导致所有字体错位

### ISSUE THREAD

**Issue by nimojs** [thx/thx.github.io#1]
http://iconfont.cn/search?q=%E7%9C%BC%E7%9D%9B

http://static-.b0.upaiyun.com/free/other/eye.png
这个眼睛加入图标项目会导致图标错位

显示截图
http://static-.b0.upaiyun.com/free/other/iconfontbug.jpg

demo压缩包：http://static-.b0.upaiyun.com/free/other/iconfont.zip

**Comment by yisibl** [comment]
cc @cricy
